
services:
  postgres:
    image: postgres:15
    container_name: jd-postgres
    environment:
      POSTGRES_DB: jd_db
      POSTGRES_USER: jd_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
